services:
  mysql:
    image: mysql:8.0
    container_name: fundflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fundflow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: fundflow-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: fundflow-backend
    restart: unless-stopped
    environment:
      PORT: 5000
      JWT_SECRET: fundflow
      MYSQL_DB: fundflow
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
      MONGO_URI: mongodb://mongo:27017/fundflow_logs
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - mongo
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: fundflow-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5000/api
    command: npm run dev
    depends_on:
      - backend

volumes:
  mysql_data:
  mongo_data:
